num1=input("enter your number:")
print("your number is:",num1)
num2=input("enter your number:")
print("your number is:",num2)
addition=int(num1)+int(num2)
print("the addition is:",addition)
print("the subtraction is:",int(num1)-int(num2))
print("the multiplication is:",int(num1)*int(num2))
print("the division is:",int(num1)/int(num2))
print("the modulus is:",int(num1)%int(num2))
print("the floor division is:",int(num1)//int(num2))
print("the exponent is:",int(num1)**int(num2))
print("the average is:",(int(num1)+int(num2))/2)
a = True
b = False
print("Value of a:", a)
print("Value of b:", b)
print("\na AND b =", a and b)
print("a OR b =", a or b)
print("NOT a =", not a)
print("NOT b =", not b)